### PR TITLE
Add singleton 'scenario' dimension for 'historical climate'

### PR DESCRIPTION
**Pull request by thenaomig**
This should fix the issue in the AMY panel that popped up after the data_loaders refactor: seems to require that there be a singleton dimension for scenario if 'Historical Climate' is present without any SSP. This PR adds one.

### CODE REVIEW

**Review by nicolejkeeney — CHANGES_REQUESTED** [review]
Doesn't seem to work for me-- still not seeing the scenario dimension/coordinate. Just using the default setting for `app.select()`. Also getting an error still from `app.explore.amy()`

Screenshot 2023-07-14 at 9 02 26 AM

**Comment by thenaomig** [comment]
Previously scenario was added as a coordinate but now it is a dimension too as desired.

**Review by nicolejkeeney — APPROVED** [review]
Your recent commit fixed the issue, thanks!

**Review by vicford — APPROVED** [review]
Works for me

**Pull request merged**
