### PR TITLE
Dynamically populate param classes

### PR DESCRIPTION
**Pull request by thenaomig**
The primary purpose of this PR is to speed up the import of climakitae. It achieves this by:
- delaying the reading of the catalog to the call to ck.Application()
- delaying the reading of area-selection shapefiles to ck.Application()
As a result, ck.Application() is slower to execute, but climakitae imports immediately, as one might expect it to.

This was accomplished by learning to pass parameter values to classes that inherit from param.Parameterized, and adding an __init__ on top of the inherited one from the metaclass for both DataSelector and LocSelectorArea classes in selectors.py. 

Then the resulting changes in core.py and data_loaders.py were brought into agreement with the new data organization. The catalog is read in core.py now, and a get_catalog_contents function was added there to get a dictionary of choices to pass to select(); this is in place of the data class that held the same content previously (plus the catalog) in selectors.py

### CODE REVIEW

**Comment by thenaomig** [comment]
Note: it will be necessary to do manual merge stuff with the select_fixes branch, which introduced additional references to a structure that this PR deprecates for selector choices.

**Comment by bkg** [comment]
Just noting the most recent commit introduced a merge conflict since it's already present on main. To update a PR with changes from main, it should be rebased with that branch. There's more info in the [GH docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/keeping-your-pull-request-in-sync-with-the-base-branch).

**Review by nabigac — COMMENTED** [review]
hi @thenaomig , 

i tried testing out this branch and received the following error when calling "app = ck.Application()":

---------------------------------------------------------------------------
CPLE_OpenFailedError                      Traceback (most recent call last)
fiona/_shim.pyx in fiona._shim.gdal_open_vector()

fiona/_err.pyx in fiona._err.exc_wrap_pointer()

CPLE_OpenFailedError: '/vsimem/5c91f85c63f74ba28d9524e99fb1acec' not recognized as a supported file format.

During handling of the above exception, another exception occurred:

DriverError                               Traceback (most recent call last)
/tmp/ipykernel_335/2946557630.py in <module>
----> 1 app = ck.Application()

/srv/conda/envs/notebook/lib/python3.9/site-packages/climakitae/core.py in __init__(self)
     22         self.selections = DataSelector(choices=_get_catalog_contents(self._cat))
     23 
---> 24         self.location = LocSelectorArea()
     25         self.user_export_format = FileTypeSelector()
     26 

/srv/conda/envs/notebook/lib/python3.9/site-packages/climakitae/selectors.py in __init__(self, **params)
    140     def __init__(self, **params):
    141         super().__init__(**params)
--> 142         self._geographies = Boundaries()
    143         self._geography_choose = self._geographies.boundary_dict()
    144         self.param["cached_area"].objects = list(

/srv/conda/envs/notebook/lib/python3.9/site-packages/climakitae/selectors.py in __init__(self)
     53     def __init__(self):
     54         self._us_states = regionmask.defined_regions.natural_earth_v4_1_0.us_states_50
---> 55         self._ca_counties = gpd.read_file(
     56             "https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/State_County/MapServer/1/query?where=STATE=06&f=geojson"
     57         )

/srv/conda/envs/notebook/lib/python3.9/site-packages/geopandas/io/file.py in _read_file(filename, bbox, mask, rows, **kwargs)
    199 
    200     with fiona_env():
--> 201         with reader(path_or_bytes, **kwargs) as features:
    202 
    203             # In a future Fiona release the crs attribute of features will

/srv/conda/envs/notebook/lib/python3.9/site-packages/fiona/collection.py in __init__(self, bytesbuf, **kwds)
    553 
    554         # Instantiate the parent class.
--> 555         super(BytesCollection, self).__init__(self.virtual_file, vsi=filetype,
    556                                               encoding='utf-8', **kwds)
    557 

/srv/conda/envs/notebook/lib/python3.9/site-packages/fiona/collection.py in __init__(self, path, mode, driver, schema, crs, encoding, layer, vsi, archive, enabled_drivers, crs_wkt, ignore_fields, ignore_geometry, **kwargs)
    160             if self.mode == 'r':
    161                 self.session = Session()
--> 162                 self.session.start(self, **kwargs)
    163             elif self.mode in ('a', 'w'):
    164                 self.session = WritingSession()

fiona/ogrext.pyx in fiona.ogrext.Session.start()

fiona/_shim.pyx in fiona._shim.gdal_open_vector()

DriverError: '/vsimem/5c91f85c63f74ba28d9524e99fb1acec' not recognized as a supported file format.

**Comment by thenaomig** [comment]
merged the latest version of main into this branch, so that since-corrected issues do not plague this branch for testing

**Review by elehmer — APPROVED** [review]
LGTM!! I loaded this branch on the Hub and everything runs smoothly.

**Review by vicford — APPROVED** [review]
Tested on the hub and locally, with no issues! Import runs smoothly and quickly, as was desired.

**Pull request merged**
