### PR TITLE
Large Data Warnings

### PR DESCRIPTION
**Pull request by elehmer**
# Description of PR

This PR adds data warnings for when users pick large amounts of data that will take long periods to run operations.

**Summary of changes and related issue**

Adding data warnings for data retrieved over 1GB in size. Data over 5GB given more emphatic message. Data over 10GB given a sever warning.

**Relevant motivation and context**

User can download very large datasets without knowing the consequences of doing so as far as run time on even the simplest of operations. As warning before retrieval is not ideal due to different paths to access the data it seemed warranted to put a warning after data retrieval but before trying to load into memory. 

**Dependencies required for this change?**

None

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

**Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.**

- [x] Tested on HUB with various data returns of different sizes.

# Checklist:

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by vicford — COMMENTED** [review]
Tested in getting_started on:
- hourly air temp 
- all of CA
- not area averaged
- 3km
- historical + ssp370
Which rightfully returns the "huge" option. My preference is to modify the warning text in this case that it is prohibitively large and that operations may not work without further subsetting. 

Otherwise, is there a way we can be more explicit? "Extra time" and "considerably more time" is somewhat vague

**Comment by elehmer** [comment]
[Can't download big file](https://trello.com/c/J4x6FNiU/564-cant-download-big-file)

**Comment by elehmer** [comment]
[Data Warning](https://trello.com/c/BZn6zD5o/612-data-warning)

**Comment by elehmer** [comment]
> Tested in getting_started on:
> 
> * hourly air temp
> * all of CA
> * not area averaged
> * 3km
> * historical + ssp370
>   Which rightfully returns the "huge" option. My preference is to modify the warning text in this case that it is prohibitively large and that operations may not work without further subsetting.
> 
> Otherwise, is there a way we can be more explicit? "Extra time" and "considerably more time" is somewhat vague

I made some ballpark guesses compared 1GB of data using `ck.load` times

**Pull request merged**
