### PR TITLE
Mapping improvements

### PR DESCRIPTION
**Pull request by nicolejkeeney**
This PR incorporates the AE branded colormaps into app.explore and app.view. 

Each variable has been assigned a default colormap, which was added as an extra column in variable_descriptions.csv. A new utils function aids in reading in the cmap text files.

### CODE REVIEW

**Review by vicford — APPROVED** [review]
Love the colormaps in action!

**Review by elehmer — APPROVED** [review]
Now we cooking with gas!!! LOL

Looks great!!

**Comment by elehmer** [comment]
I'm wondering if there is a way to only store the RGB colormap and convert to HEX on the fly? That way we only have to maintain one set and they won't diverge over time by accident. This could be an improvement we make later after launch...

Here is one possible way I think:
https://stackoverflow.com/questions/33596491/extract-matplotlib-colormap-in-hex-format

**Comment by nicolejkeeney** [comment]
> I'm wondering if there is a way to only store the RGB colormap and convert to HEX on the fly? That way we only have to maintain one set and they won't diverge over time by accident. This could be an improvement we make later after launch...
> 
> Here is one possible way I think: https://stackoverflow.com/questions/33596491/extract-matplotlib-colormap-in-hex-format

Agreed that this would be a better method. Will check this out. Thanks!

**Comment by elehmer** [comment]
This method looks even better: https://www.tutorialspoint.com/extract-matplotlib-colormap-in-hex-format

**Comment by elehmer** [comment]
> > I'm wondering if there is a way to only store the RGB colormap and convert to HEX on the fly? That way we only have to maintain one set and they won't diverge over time by accident. This could be an improvement we make later after launch...
> > Here is one possible way I think: https://stackoverflow.com/questions/33596491/extract-matplotlib-colormap-in-hex-format
> 
> Agreed that this would be a better method. Will check this out. Thanks!

This method looks clean and efficient: https://www.tutorialspoint.com/extract-matplotlib-colormap-in-hex-format

**Comment by nicolejkeeney** [comment]
> > > I'm wondering if there is a way to only store the RGB colormap and convert to HEX on the fly? That way we only have to maintain one set and they won't diverge over time by accident. This could be an improvement we make later after launch...
> > > Here is one possible way I think: https://stackoverflow.com/questions/33596491/extract-matplotlib-colormap-in-hex-format
> > 
> > 
> > Agreed that this would be a better method. Will check this out. Thanks!
> 
> This method looks clean and efficient: https://www.tutorialspoint.com/extract-matplotlib-colormap-in-hex-format

Just implemented it! Thanks for this tip

**Review by elehmer — APPROVED** [review]
Awesomeness!! Love the minimizing of code!!

**Comment by vicford** [comment]
Now works on the hub for app.explore without kernel crashing! Huzzah!

**Pull request merged**
