### PR TITLE
Add back in grid_mapping attribute for relative humidity

### PR DESCRIPTION
**Pull request by nicolejkeeney**
**Information:** The grid_mapping attribute is lost for some reason by the metpy function that computes relative humidity in our derive_variables module. This is causing issues with reprojecting the data, as grid_mapping is used by rioxarray to determine information about the data's CRS. In this PR, I just add back in that attribute. 

**To test:** Try just selecting relative humidity from app.select() and make sure the attribute "grid_mapping" appears.

### CODE REVIEW

**Review by vicford — APPROVED** [review]
grid_mapping = Lambert_Conformal 

back in, whoop

**Comment by elehmer** [comment]
Hmm, yeah looking at the `metpy` docs  it looks like a dimension-less quantity (relative humidity) is returned and so they didn't think the attrs would be needed? I don't see any handles inside the library to change any of this behavior. Are all attrs lost or just the `grid_mapping` one? Anyway, this might be the most expedient way to deal with this issue.

**Comment by nicolejkeeney** [comment]
> 

Weirdly, it seems like only the grid_mapping attr is lost.

**Comment by nicolejkeeney** [comment]
> Hmm, yeah looking at the `metpy` docs it looks like a dimension-less quantity (relative humidity) is returned and so they didn't think the attrs would be needed? I don't see any handles inside the library to change any of this behavior. Are all attrs lost or just the `grid_mapping` one? Anyway, this might be the most expedient way to deal with this issue.

I just checked and the variables that go into that metpy function all have the grid_mapping function, yet the output does not? It maintains the other attributes though. I don't understand why.

**Comment by elehmer** [comment]
It must happen at the `calc` stage as the `dequantify` does a `copy` which is a deep copy by default so the attrs should come with. Have you tried integrating `parse_cf` into the code somewhere?

https://unidata.github.io/MetPy/latest/api/generated/metpy.xarray.html?highlight=dequantify#metpy.xarray.MetPyDataArrayAccessor.dequantify

It's on this page. Also maybe the `assign_crs` method might help?

**Comment by nicolejkeeney** [comment]
> It must happen at the `calc` stage as the `dequantify` does a `copy` which is a deep copy by default so the attrs should come with. Have you tried integrating `parse_cf` into the code somewhere?
> 
> https://unidata.github.io/MetPy/latest/api/generated/metpy.xarray.html?highlight=dequantify#metpy.xarray.MetPyDataArrayAccessor.dequantify
> 
> It's on this page. Also maybe the `assign_crs` method might help?

What do you mean? Is this an argument to metpy.calc.relative_humidity_from_mixing_ratio? 

I shouldn't need to assign a crs. I really just need grid_mapping as an attribute set to Lambert_Conformal. You're right that something weird is going on under the hood where the function removes that attribute.

**Review by bethmints — APPROVED** [review]
the attribute grid_mapping is in the data array obtained by app.select()

**Pull request merged**
