### PR TITLE
Add helper function to return julian day bounds for AMY months

### PR DESCRIPTION
**Pull request by nicolejkeeney**
This is a helper function used in the AMY notebook.

### CODE REVIEW

**Review by vicford — APPROVED** [review]
Thanks for grabbing this in! 

Tested in the revised explore_amy notebook in the `amy_usability_improvements` branch on cae-examples :)

**Comment by nicolejkeeney** [comment]
> Tested in the revised explore_amy notebook in the `amy_usability_improvements` branch on cae-examples :)

Oooo can you retest then actually? This branch is called `amy_months`, I will delete the old branch `amy_usability_improvements` now. Sorry for the confusion.

**Review by elehmer — APPROVED** [review]
LGTM!

**Comment by vicford** [comment]
> Oooo can you retest then actually? This branch is called `amy_months`, I will delete the old branch `amy_usability_improvements` now. Sorry for the confusion.

Sorry, also to clarify: the **AMY notebook improvements branch** is called `amy_usability_improvements`, I tested that version of the notebook with the `amy_months` climakitae branch

**Comment by nicolejkeeney** [comment]
> > Oooo can you retest then actually? This branch is called `amy_months`, I will delete the old branch `amy_usability_improvements` now. Sorry for the confusion.
> 
> Sorry, also to clarify: the **AMY notebook improvements branch** is called `amy_usability_improvements`, I tested that version of the notebook with the `amy_months` climakitae branch

Ah perfect okay! Sounds great.

**Pull request merged**
