### PR TITLE
Adding functionality to WL to allow for users to select a singular model

### PR DESCRIPTION
**Pull request by claalmve**
# Description of PR

### Summary of changes and related issue
Allows for selection of specific simulations/models for WLs.

### Relevant motivation and context
WLs did not support this functionality before, but now you can select a singular model (or subset of models) like you would be able to through `selections.simulation`.

### Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

<br>

#### Practical
- [x] 80% unit test coverage
- [x] Documentation
  - [ ] All functions/adjusted functions documented in the [readthedocs](https://climakitae.readthedocs.io/en/latest/).
  - [ ] Documentation is pushed
- [x] Complex code commented
- [x] Naming conventions followed
  - [ ] Helper functions hidden with `_` before the name
- [x] Context of function is clearly provided
  - [ ] Intent of function is provided
  - [ ] How to test, so that it is not siloed on scientists and anyone can review
  - [ ] Appropriate manual testing was completed
- [x] Any notebooks known to utilize the affected functions are still working
- [x] Linting completed and resolved

#### Conceptual
- [x] Doesn't replicate existing functionality
- [x] Aligns with general coding standard of existing functions
- [x] Matches desired functinonality from users/scientists

### CODE REVIEW

**Comment by vicford** [comment]
Getting this issue in testing: 

```
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
Cell In [3], line 13
     11 wl.wl_params.simulation = ['WRF_MIROC6_r1i1p1f1_Historical + SSP 3-7.0 -- Business as Usual']
     12 wl.wl_params.anom = 'No'
---> 13 wl.calculate()
     15 proj_ds = wl.sliced_data['2.0']
     16 proj_ds = add_dummy_time_to_wl(proj_ds)

File ~/src/climakitae/climakitae/explore/warming.py:86, in WarmingLevels.calculate(self)
     80 self.wl_params.scenario_ssp = [
     81     "SSP 3-7.0 -- Business as Usual",
     82     "SSP 2-4.5 -- Middle of the Road",
     83     "SSP 5-8.5 -- Burn it All",
     84 ]
     85 # Postage data and anomalies
---> 86 self.catalog_data = self.wl_params.retrieve()
     87 self.catalog_data = self.catalog_data.stack(all_sims=["simulation", "scenario"])
     89 # For WRF, dropping invalid simulations before doing any other computation

File ~/src/climakitae/climakitae/core/data_interface.py:1208, in DataParameters.retrieve(self, config, merge)
   1204     else:
   1205         raise ValueError(
   1206             "To retrieve data specified in a configuration file, please input the path to your local configuration csv as a string"
   1207         )
-> 1208 data_return = read_catalog_from_select(self)
   1210 if isinstance(data_return, list):
   1211     for l in data_return:

File ~/src/climakitae/climakitae/core/data_load.py:1157, in read_catalog_from_select(selections)
   1155     da = _get_hourly_specific_humidity(selections)
   1156 elif orig_var_id_selection == "fosberg_index_derived":  # Hourly
-> 1157     da = _get_fosberg_fire_index(selections)
   1158 elif orig_var_id_selection == "noaa_heat_index_derived":  # Hourly
   1159     da = _get_noaa_heat_index(selections)

File ~/src/climakitae/climakitae/core/data_load.py:1094, in read_catalog_from_select.<locals>._get_fosberg_fire_index(selections)
   1092 selections.variable_id = ["t2"]
   1093 selections.units = "degC"  # Kelvin required for humidity
-> 1094 t2_da_C = _get_data_one_var(selections)
   1096 # Load mixing ratio data
   1097 selections.variable_id = ["q2"]

File ~/src/climakitae/climakitae/core/data_load.py:664, in _get_data_one_var(selections)
    661     data_dict = {**data_dict, **data_dict2}
    663 # Merge individual Datasets into one DataArray object.
--> 664 da = _merge_all(selections=selections, data_dict=data_dict)
    666 # Set data attributes and name
    667 native_units = da.attrs["units"]

File ~/src/climakitae/climakitae/core/data_load.py:592, in _merge_all(selections, data_dict)
    589         all_ssps = _add_scenario_dim(all_ssps, "Historical Reconstruction")
    591 # Rename expanded dimension:
--> 592 all_ssps = all_ssps.rename({"member_id": "simulation"})
    594 # Convert to xr.DataArray:
    595 var_id = list(all_ssps.data_vars)[0]

UnboundLocalError: local variable 'all_ssps' referenced before assignment
```

**Comment by claalmve** [comment]
I think this will work if you just pass the GCM names into the `wl_params` simulations instead, like `wl.wl_params.simulation = ['MIROC6']`.

**Comment by vicford** [comment]
> I think this will work if you just pass the GCM names into the `wl_params` simulations instead, like `wl.wl_params.simulation = ['MIROC6']`.

@claalmve does the order matter? Sometimes the argument order for WL/selections does matter

**Comment by claalmve** [comment]
> > I think this will work if you just pass the GCM names into the `wl_params` simulations instead, like `wl.wl_params.simulation = ['MIROC6']`.
> 
> @claalmve does the order matter? Sometimes the argument order for WL/selections does matter

I think as long as these are set after the downscaling method, it should be okay.

**Pull request merged**
