### PR TITLE
app.select() panel changes

### PR DESCRIPTION
**Pull request by nicolejkeeney**
This panel improves the data options in the app.select() panel. Now, you should never be able to retrieve Historical Reconstruction data and SSP data together. 

1. Adds descriptive text describing the options 
2. Raises a warning if the user tries to select historical data and SSP data without selecting Append Historical Climate 
3. Doesn't allow the user to select Historical Reconstruction data and SSP data together 

**To test:** Just try selecting different options and calling app.retrieve() to make sure that the data is returned as expected. 

For example, for a subset of selections, the new panel looks like this: 

app select

### CODE REVIEW

**Review by vicford — CHANGES_REQUESTED** [review]
1. Looks like the SSP name options in the selection panel do not match what is displayed in the updating graph... as in:
Selecting 2-4.5 pulls up 3-7.0
Selecting 3-7.0 pulls up 5-8.5
Selecting 5-8.5 pulls up 2-4.5 

**Example:**
Screen Shot 2022-11-03 at 1 10 31 PM


2. Can we also reorder the bars in the graph so that the order is 2-4.5, 3-7.0, 5-8.5? At present it's 2-4.5, 5-8.5, 3-7.0 
Screen Shot 2022-11-03 at 1 06 41 PM

I like the explanatory text on these options!

**Comment by nicolejkeeney** [comment]
> 1. Looks like the SSP name options in the selection panel do not match what is displayed in the updating graph... as in:
>    Selecting 2-4.5 pulls up 3-7.0
>    Selecting 3-7.0 pulls up 5-8.5
>    Selecting 5-8.5 pulls up 2-4.5
>    This also persists into what data is retrieved too. Selection of 5-8.5 returns 2-4.5

Good catch!!! Thank you!! Fixed!

**Review by vicford — APPROVED** [review]
Nice, data selects as desired. Like all the useful hints!

**Comment by bkg** [comment]
What do you think about removing the "Append Historical Climate" checkbox entirely, and if a user checks "Historical Climate" and an SSP, just append it for them? That way, they don't need to figure out which options are compatible.

Also, could you use radio buttons which are intended for mutually exclusive options instead of checkboxes for the historical selection? There's still the problem with nans inserted for missing time steps when they are combined. Or, if it's desirable to combine them, use an inner instead of an outer join.

**Comment by nicolejkeeney** [comment]
> What do you think about removing the "Append Historical Climate" checkbox entirely, and if a user checks "Historical Climate" and an SSP, just append it for them? That way, they don't need to figure out which options are compatible.

I think thats a great idea. I will check with Naomi and see what she thinks.

**Review by bethmints — APPROVED** [review]
looks good to me! ideally boxes will be unchecked if they're incompatible, but I'm guessing that's not a possibility.

**Comment by bethmints** [comment]
oh - it looks like you and Brian are already talking about dealing with incompatible options. awesome!

**Review by vicford — APPROVED** [review]
Love the updated version!

**Review by elehmer — CHANGES_REQUESTED** [review]
This works well except for the historical reconstruction error message does not reset after reselecting historical or deselecting any historical. Is there a way to clear this message when his. recon. unchecked?

**Comment by elehmer** [comment]
> This works well except for the historical reconstruction error message does not reset after reselecting historical or deselecting any historical. Is there a way to clear this message when his. recon. unchecked?

I see also that you remove his. recon. from the list but it doesn't update the checkboxes (flaw of the CheckBoxGroup). I wonder if there is a way to do a callback on CheckBoxGroup list update?

**Comment by nicolejkeeney** [comment]
> > This works well except for the historical reconstruction error message does not reset after reselecting historical or deselecting any historical. Is there a way to clear this message when his. recon. unchecked?
> 
> I see also that you remove his. recon. from the list but it doesn't update the checkboxes (flaw of the CheckBoxGroup). I wonder if there is a way to do a callback on CheckBoxGroup list update?

If there is a way to do this, I'm not sure how. Makes me irritated. Damn panel!

**Comment by nicolejkeeney** [comment]
> > This works well except for the historical reconstruction error message does not reset after reselecting historical or deselecting any historical. Is there a way to clear this message when his. recon. unchecked?
> 
> I see also that you remove his. recon. from the list but it doesn't update the checkboxes (flaw of the CheckBoxGroup). I wonder if there is a way to do a callback on CheckBoxGroup list update?

Through a roundabout method, I believe I have just fixed this issue if you want to take another look!

**Comment by elehmer** [comment]
> > > This works well except for the historical reconstruction error message does not reset after reselecting historical or deselecting any historical. Is there a way to clear this message when his. recon. unchecked?
> > 
> > 
> > I see also that you remove his. recon. from the list but it doesn't update the checkboxes (flaw of the CheckBoxGroup). I wonder if there is a way to do a callback on CheckBoxGroup list update?
> 
> Through a roundabout method, I believe I have just fixed this issue if you want to take another look!

Oh! I was just setting up to attack this from the very same direction!! I'll have a look! Thanks!

**Comment by elehmer** [comment]
> > > > This works well except for the historical reconstruction error message does not reset after reselecting historical or deselecting any historical. Is there a way to clear this message when his. recon. unchecked?
> > > 
> > > 
> > > I see also that you remove his. recon. from the list but it doesn't update the checkboxes (flaw of the CheckBoxGroup). I wonder if there is a way to do a callback on CheckBoxGroup list update?
> > 
> > 
> > Through a roundabout method, I believe I have just fixed this issue if you want to take another look!
> 
> Oh! I was just setting up to attack this from the very same direction!! I'll have a look! Thanks!

Looks great! One thing is if they go ahead and run `app.retrieve` with error message showing the code bombs out:

```
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
/tmp/ipykernel_1091/3536534344.py in <module>
----> 1 data_to_use = app.retrieve()

~/cae-notebooks/src/climakitae/climakitae/core.py in retrieve(self)
     71         """
     72         # TODO: insert additional 'hang in there' statement if it's taking a while
---> 73         return _read_from_catalog(self.selections, self.location, self._cat)
     74 
     75     # === View =======================================

~/cae-notebooks/src/climakitae/climakitae/data_loaders.py in _read_from_catalog(selections, location, cat)
    409 
    410     else:
--> 411         da = _get_data_one_var(selections, location, cat)
    412 
    413     # Convert units

~/cae-notebooks/src/climakitae/climakitae/data_loaders.py in _get_data_one_var(selections, location, cat)
    318 
    319     # Merge individual Datasets into one DataArray object.
--> 320     da = _process_and_concat(
    321         selections=selections, location=location, dsets=data_dict, cat_subset=cat_subset
    322     )

~/cae-notebooks/src/climakitae/climakitae/data_loaders.py in _process_and_concat(selections, location, dsets, cat_subset)
    210         da_name = _scenario_to_experiment_id(scenario)
    211         for simulation in selections.simulation:
--> 212             if append_historical:
    213                 # Reset name
    214                 da_name = "Historical + " + scenario

UnboundLocalError: local variable 'append_historical' referenced before assignment
```

We should probably trap for this and error out more gently...

**Comment by nicolejkeeney** [comment]
> > > > > This works well except for the historical reconstruction error message does not reset after reselecting historical or deselecting any historical. Is there a way to clear this message when his. recon. unchecked?
> > > > 
> > > > 
> > > > I see also that you remove his. recon. from the list but it doesn't update the checkboxes (flaw of the CheckBoxGroup). I wonder if there is a way to do a callback on CheckBoxGroup list update?
> > > 
> > > 
> > > Through a roundabout method, I believe I have just fixed this issue if you want to take another look!
> > 
> > 
> > Oh! I was just setting up to attack this from the very same direction!! I'll have a look! Thanks!
> 
> Looks great! One thing is if they go ahead and run `app.retrieve` with error message showing the code bombs out:
> 
> ```
> ---------------------------------------------------------------------------
> UnboundLocalError                         Traceback (most recent call last)
> /tmp/ipykernel_1091/3536534344.py in <module>
> ----> 1 data_to_use = app.retrieve()
> 
> ~/cae-notebooks/src/climakitae/climakitae/core.py in retrieve(self)
>      71         """
>      72         # TODO: insert additional 'hang in there' statement if it's taking a while
> ---> 73         return _read_from_catalog(self.selections, self.location, self._cat)
>      74 
>      75     # === View =======================================
> 
> ~/cae-notebooks/src/climakitae/climakitae/data_loaders.py in _read_from_catalog(selections, location, cat)
>     409 
>     410     else:
> --> 411         da = _get_data_one_var(selections, location, cat)
>     412 
>     413     # Convert units
> 
> ~/cae-notebooks/src/climakitae/climakitae/data_loaders.py in _get_data_one_var(selections, location, cat)
>     318 
>     319     # Merge individual Datasets into one DataArray object.
> --> 320     da = _process_and_concat(
>     321         selections=selections, location=location, dsets=data_dict, cat_subset=cat_subset
>     322     )
> 
> ~/cae-notebooks/src/climakitae/climakitae/data_loaders.py in _process_and_concat(selections, location, dsets, cat_subset)
>     210         da_name = _scenario_to_experiment_id(scenario)
>     211         for simulation in selections.simulation:
> --> 212             if append_historical:
>     213                 # Reset name
>     214                 da_name = "Historical + " + scenario
> 
> UnboundLocalError: local variable 'append_historical' referenced before assignment
> ```
> 
> We should probably trap for this and error out more gently...

Bleh, this probably has to do with the fact that we just merged another PR to main, and I just merged main into this PR. Will look into it now.

**Comment by nicolejkeeney** [comment]
> > > > > This works well except for the historical reconstruction error message does not reset after reselecting historical or deselecting any historical. Is there a way to clear this message when his. recon. unchecked?
> > > > 
> > > > 
> > > > I see also that you remove his. recon. from the list but it doesn't update the checkboxes (flaw of the CheckBoxGroup). I wonder if there is a way to do a callback on CheckBoxGroup list update?
> > > 
> > > 
> > > Through a roundabout method, I believe I have just fixed this issue if you want to take another look!
> > 
> > 
> > Oh! I was just setting up to attack this from the very same direction!! I'll have a look! Thanks!
> 
> Looks great! One thing is if they go ahead and run `app.retrieve` with error message showing the code bombs out:
> 
> ```
> ---------------------------------------------------------------------------
> UnboundLocalError                         Traceback (most recent call last)
> /tmp/ipykernel_1091/3536534344.py in <module>
> ----> 1 data_to_use = app.retrieve()
> 
> ~/cae-notebooks/src/climakitae/climakitae/core.py in retrieve(self)
>      71         """
>      72         # TODO: insert additional 'hang in there' statement if it's taking a while
> ---> 73         return _read_from_catalog(self.selections, self.location, self._cat)
>      74 
>      75     # === View =======================================
> 
> ~/cae-notebooks/src/climakitae/climakitae/data_loaders.py in _read_from_catalog(selections, location, cat)
>     409 
>     410     else:
> --> 411         da = _get_data_one_var(selections, location, cat)
>     412 
>     413     # Convert units
> 
> ~/cae-notebooks/src/climakitae/climakitae/data_loaders.py in _get_data_one_var(selections, location, cat)
>     318 
>     319     # Merge individual Datasets into one DataArray object.
> --> 320     da = _process_and_concat(
>     321         selections=selections, location=location, dsets=data_dict, cat_subset=cat_subset
>     322     )
> 
> ~/cae-notebooks/src/climakitae/climakitae/data_loaders.py in _process_and_concat(selections, location, dsets, cat_subset)
>     210         da_name = _scenario_to_experiment_id(scenario)
>     211         for simulation in selections.simulation:
> --> 212             if append_historical:
>     213                 # Reset name
>     214                 da_name = "Historical + " + scenario
> 
> UnboundLocalError: local variable 'append_historical' referenced before assignment
> ```
> 
> We should probably trap for this and error out more gently...

@elehmer This should be fixed now!

**Comment by elehmer** [comment]
> > > > > > This works well except for the historical reconstruction error message does not reset after reselecting historical or deselecting any historical. Is there a way to clear this message when his. recon. unchecked?
> > > > > 
> > > > > 
> > > > > I see also that you remove his. recon. from the list but it doesn't update the checkboxes (flaw of the CheckBoxGroup). I wonder if there is a way to do a callback on CheckBoxGroup list update?
> > > > 
> > > > 
> > > > Through a roundabout method, I believe I have just fixed this issue if you want to take another look!
> > > 
> > > 
> > > Oh! I was just setting up to attack this from the very same direction!! I'll have a look! Thanks!
> > 
> > 
> > Looks great! One thing is if they go ahead and run `app.retrieve` with error message showing the code bombs out:
> > ```
> > ---------------------------------------------------------------------------
> > UnboundLocalError                         Traceback (most recent call last)
> > /tmp/ipykernel_1091/3536534344.py in <module>
> > ----> 1 data_to_use = app.retrieve()
> > 
> > ~/cae-notebooks/src/climakitae/climakitae/core.py in retrieve(self)
> >      71         """
> >      72         # TODO: insert additional 'hang in there' statement if it's taking a while
> > ---> 73         return _read_from_catalog(self.selections, self.location, self._cat)
> >      74 
> >      75     # === View =======================================
> > 
> > ~/cae-notebooks/src/climakitae/climakitae/data_loaders.py in _read_from_catalog(selections, location, cat)
> >     409 
> >     410     else:
> > --> 411         da = _get_data_one_var(selections, location, cat)
> >     412 
> >     413     # Convert units
> > 
> > ~/cae-notebooks/src/climakitae/climakitae/data_loaders.py in _get_data_one_var(selections, location, cat)
> >     318 
> >     319     # Merge individual Datasets into one DataArray object.
> > --> 320     da = _process_and_concat(
> >     321         selections=selections, location=location, dsets=data_dict, cat_subset=cat_subset
> >     322     )
> > 
> > ~/cae-notebooks/src/climakitae/climakitae/data_loaders.py in _process_and_concat(selections, location, dsets, cat_subset)
> >     210         da_name = _scenario_to_experiment_id(scenario)
> >     211         for simulation in selections.simulation:
> > --> 212             if append_historical:
> >     213                 # Reset name
> >     214                 da_name = "Historical + " + scenario
> > 
> > UnboundLocalError: local variable 'append_historical' referenced before assignment
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > We should probably trap for this and error out more gently...
> 
> @elehmer This should be fixed now!

Yes it is!!! I approve!!

**Review by elehmer — APPROVED** [review]

**Pull request merged**
