### PR TITLE
Rework code after ensmean data was added to main data catalog

### PR DESCRIPTION
**Pull request by nicolejkeeney**
Just had to modify the code a bit to account for the ensemble mean data now being available in our main data catalog. This required me to add simulation as a parameter to app.select, such that app.explore.tmy could select for just the ensmean data, and app.select could ignore the ensmean data (and not return it as an additional simulation). 

I realize the explanation is a bit confusing. Feel free to add questions here for additional clarity and I will respond and try to clear up any confusion. 

**Once this PR is approved, I will merge it as the same time as the amy_cached_data branch**

**To test:** Just try running app.retrieve() for different datasets. Also try running app.explore.amy(). Thanks! 

_Note to self: Need to confirm that this doesn't cause any issues with the notebooks in cae-notebooks before merging as well._

### CODE REVIEW

**Review by vicford — APPROVED** [review]
Confirmed that:
1. app.explore.amy works as intended
2. app.select + app.retrieve does not return ensmean as a simulation option

**Comment by elehmer** [comment]
Hmm, I am still seeing `ensmean` after `app.retrieve` but after `app.explore.tmy` is called.

image

**Comment by elehmer** [comment]
> Hmm, I am still seeing `ensmean` after `app.retrieve` but after `app.explore.tmy` is called.
> 
> image
> 
> Going straight to `app.select` + `app.retrieve` works...

Hmm, now not seeing this. Maybe the code wasn't loading in the first notebook...

**Comment by elehmer** [comment]
> > Hmm, I am still seeing `ensmean` after `app.retrieve` but after `app.explore.tmy` is called.
> > image
> > Going straight to `app.select` + `app.retrieve` works...
> 
> Hmm, now not seeing this. Maybe the code wasn't loading in the first notebook...

So if you call `app.select` after `app.explore.amy()` and don't change anything you get the `ensmean` only that was used for amy. Do we need some sort of reset to defaults for `app.select`?

**Comment by vicford** [comment]
> If someone uses `app.select` or `app.retrieve` after the very specific `amy` code we want it to return the other simulations right

Actually, no! The AMY requires an ensemble mean at present :) The original calculation was computing ensemble mean on the fly, and now this switches in the ensemble mean cached product instead. Presumably, in the future _someone_ might want to calculate AMY for each individual model and compare, but that's not necessary atm

**Comment by elehmer** [comment]
> > So if you call `app.select` after `app.explore.amy()` and don't change anything you get the `ensmean` only that was used for amy. Do we need some sort of reset to defaults for `app.select`?
> 
> You are absolutely right that the defaults need to be reset. Thank you so much for catching this!

GUIs are tricky!! (And should be avoid like the plague lol)

**Comment by nicolejkeeney** [comment]
> GUIs are tricky!! (And should be avoided like the plague lol)

I think I fixed the issue with my most recent commit!

**Comment by elehmer** [comment]
> > GUIs are tricky!! (And should be avoided like the plague lol)
> 
> I think I fixed the issue with my most recent commit!

I'm now getting the all the simulations including `ensmean` if I do `app.select` (don't touch anything) + `app.retrieve` after amy. Is that what we want?

**Comment by nicolejkeeney** [comment]
> > > GUIs are tricky!! (And should be avoided like the plague lol)
> > 
> > 
> > I think I fixed the issue with my most recent commit!
> 
> I'm now getting the all the simulations including `ensmean` if I do `app.select` (don't touch anything) + `app.retrieve` after amy. Is that what we want?

No... not the desired behavior... darn. Will fix now.

**Comment by nicolejkeeney** [comment]
> > > GUIs are tricky!! (And should be avoided like the plague lol)
> > 
> > 
> > I think I fixed the issue with my most recent commit!
> 
> I'm now getting the all the simulations including `ensmean` if I do `app.select` (don't touch anything) + `app.retrieve` after amy. Is that what we want?

Can't seem to get it to replicate this. Can you check one more time? This is such a frustrating bug!

**Comment by elehmer** [comment]
> > > > GUIs are tricky!! (And should be avoided like the plague lol)
> > > 
> > > 
> > > I think I fixed the issue with my most recent commit!
> > 
> > 
> > I'm now getting the all the simulations including `ensmean` if I do `app.select` (don't touch anything) + `app.retrieve` after amy. Is that what we want?
> 
> Can't seem to get it to replicate this. Can you check one more time? This is such a frustrating bug!

You read my mind. I was about to check this again as I'm wondering if the codebase didn't update. Annoying when it does that!

**Comment by nicolejkeeney** [comment]
> > > > > GUIs are tricky!! (And should be avoided like the plague lol)
> > > > 
> > > > 
> > > > I think I fixed the issue with my most recent commit!
> > > 
> > > 
> > > I'm now getting the all the simulations including `ensmean` if I do `app.select` (don't touch anything) + `app.retrieve` after amy. Is that what we want?
> > 
> > 
> > Can't seem to get it to replicate this. Can you check one more time? This is such a frustrating bug!
> 
> You read my mind. I was about to check this again as I'm wondering if the codebase didn't update. Annoying when it does that!

Sweet let me know what you find!

**Review by elehmer — APPROVED** [review]

**Comment by nicolejkeeney** [comment]
> > > > > > > GUIs are tricky!! (And should be avoided like the plague lol)
> > > > > > 
> > > > > > 
> > > > > > I think I fixed the issue with my most recent commit!
> > > > > 
> > > > > 
> > > > > I'm now getting the all the simulations including `ensmean` if I do `app.select` (don't touch anything) + `app.retrieve` after amy. Is that what we want?
> > > > 
> > > > 
> > > > Can't seem to get it to replicate this. Can you check one more time? This is such a frustrating bug!
> > > 
> > > 
> > > You read my mind. I was about to check this again as I'm wondering if the codebase didn't update. Annoying when it does that!
> > 
> > 
> > Sweet let me know what you find!
> 
> Ok, my bad. Works as you designed! I need to remember to load it twice on the HUB I guess. Silly!

No worries thanks for checking that again!

**Comment by vicford** [comment]
No ensmeans to be found on my end (with app.retrieve), but works as should for amy!

**Pull request merged**
