### PR TITLE
DataInterface updates: Adding select by time or warming level approach

### PR DESCRIPTION
**Pull request by nicolejkeeney**
# Description of PR
This PR is linked to [PR #10 in climakitaegui](https://github.com/cal-adapt/climakitaegui/pull/10). 

I made some big design changes to the selections GUI to enable users to select by a time-based or a warming level approach. Can folks play around with the GUI, let me know what you think about the layout and make sure all the buttons update appropriately? 

I'll merge this later, once I finish setting up the backend retrieval. This is just a front-end change... you still can't retrieve by warming level yet. 

Also curious what people think the defaults should be: time-based or warming level? And, if warming level is selected, what should be the default warming level selection(s)? Right now I have it set to 2 deg C. We could do a different one, or more (i.e. 2, 3, and 4 deg C). 

**NOTE**: You need to be in the branch ```wl2``` in climakitaegui to test this branch! Make sure both branches are updated. 

### Summary of changes and related issue
I modified the DataInterface object to add selection options for warming level and retrieval option. I changed and added some dynamically-updating panel functions that enable the options to change depending on the user selections. 

### Relevant motivation and context
This is part of a larger push to integrate a warming-levels approach into climakitae. 

### Type of change
This is a breaking change, so it will not be merged yet. It will also require a documentation update (not in the code, but in the markdown of our notebooks) that I will need to work with the team on before it is merged. 
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

<br>

#### Practical
- [x] 80% unit test coverage
- [x] Documentation
  - [x] All functions/adjusted functions documented in the [readthedocs](https://climakitae.readthedocs.io/en/latest/).
  - [x] Documentation is pushed
- [x] Complex code commented
- [x] Naming conventions followed
  - [x] Helper functions hidden with `_` before the name
- [x] Context of function is clearly provided
  - [x] Intent of function is provided
  - [x] How to test, so that it is not siloed on scientists and anyone can review
  - [x] Appropriate manual testing was completed
- [ ] Any notebooks known to utilize the affected functions are still working
- [x] Linting completed and resolved

#### Conceptual
- [x] Doesn't replicate existing functionality
- [x] Aligns with general coding standard of existing functions
- [x] Matches desired functinonality from users/scientists

### CODE REVIEW

**Review by vicford — COMMENTED** [review]
This is fantastic @nicolejkeeney. Tested on the hub with no problems. Some general feedback: 
- I think we should rename "Retrieval Method" to "Approach" to be explicitly clear with the WL and time-based sections what is referring to what. At least in the GUI panel itself for the label in the top bar, not necessarily in the backend code if that's a hassle. 
- For WL, do we have 0.5, 3.5 as actual viable options? I know we have 1.5 and 2.5 now
- My slight preference was to have WL approach and time approach listed in the order they appear in the "retrieval method" but that puts WL at the bottom, and I like having it more front and center, especially since it is a smaller bar. I do think having 2.0°C be the default selection for GWL is good. 
- All buttons update as they should
- We need to have a collective think on whether station data should be available with GWL approach. If we keep, order of operations should be: quantile mapping first to adjust to observations, then retrieve the sliced data.

**Comment by nicolejkeeney** [comment]
> * We need to have a collective think on whether station data should be available with GWL approach. If we keep, order of operations should be: quantile mapping first to adjust to observations, then retrieve the sliced data.

Good point, hadn't thought about that. For the time being, I have removed station data for an option when using a warming levels approach.

**Comment by nicolejkeeney** [comment]
> * I think we should rename "Retrieval Method" to "Approach" to be explicitly clear with the WL and time-based sections what is referring to what. At least in the GUI panel itself for the label in the top bar, not necessarily in the backend code if that's a hassle.

After some thought, I agree and have changed it to Approach in the front end and back end in the subsequent branch ("wl3")

**Comment by nicolejkeeney** [comment]
Closing due to changes incorporated into subsequent branch ``wl3``, which is being reviewed in a separate PR.

**Pull request closed without merging**
