### PR TITLE
Rewrite map_view to be an attribute of DataSelectors

### PR DESCRIPTION
**Pull request by nicolejkeeney**
This is a purely backend change, the user won't notice anything different. Now, map_view is an attribute of DataSelectors instead of Application. This cleans up the code quite a lot. 

**To test:** Just play around with climakitae (i.e. `app.select()`, `app.view()`, `app.explore`...) and make sure you don't find any weird bugs with the display of the map in the panel.

### CODE REVIEW

**Comment by vicford** [comment]
Related to the notebooks PR, app.explore.warming didn't work for me, but app.explore.amy() was just fine

**Comment by nicolejkeeney** [comment]
> Related to the notebooks PR, app.explore.warming didn't work for me, but app.explore.amy() was just fine

Great catch, I just fixed ``app.explore.warming_levels``

**Comment by vicford** [comment]
> Great catch, I just fixed `app.explore.warming_levels`

Oooh, now getting this error
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/tmp/ipykernel_1056/2034446390.py in <module>
----> 1 app.explore.warming_levels()

~/src/climakitae/climakitae/explore.py in warming_levels(self)
     87     def warming_levels(self):
     88         """Display Warming Levels panel."""
---> 89         warming_data = _WarmingLevels(
     90             selections=self.selections, location=self.location, cat=self._cat
     91         )

~/src/climakitae/climakitae/warming_levels.py in __init__(self, *args, **params)
    234             selections=self.selections, location=self.location, cat=self.cat
    235         )
--> 236         self._warm_all_anoms = get_anomaly_data(data=self.postage_data, warmlevel=1.5)
    237 
    238         self.cmap = _read_ae_colormap(cmap="ae_orange", cmap_hex=True)

~/src/climakitae/climakitae/warming_levels.py in get_anomaly_data(data, warmlevel, scenario)
    100         gwl_times_subset = gwl_times[
    101             (gwl_times["simulation"] == sim_str)
--> 102             & (gwl_times["run"] == sim_and_runs_dict[sim_str])
    103             & (gwl_times["scenario"] == scenario)
    104         ]

KeyError: 'WRF_CESM2_r11i1p1f1'
```

**Comment by nicolejkeeney** [comment]
> > Great catch, I just fixed `app.explore.warming_levels`
> 
> Oooh, now getting this error
> 
> ```
> ---------------------------------------------------------------------------
> KeyError                                  Traceback (most recent call last)
> /tmp/ipykernel_1056/2034446390.py in <module>
> ----> 1 app.explore.warming_levels()
> 
> ~/src/climakitae/climakitae/explore.py in warming_levels(self)
>      87     def warming_levels(self):
>      88         """Display Warming Levels panel."""
> ---> 89         warming_data = _WarmingLevels(
>      90             selections=self.selections, location=self.location, cat=self._cat
>      91         )
> 
> ~/src/climakitae/climakitae/warming_levels.py in __init__(self, *args, **params)
>     234             selections=self.selections, location=self.location, cat=self.cat
>     235         )
> --> 236         self._warm_all_anoms = get_anomaly_data(data=self.postage_data, warmlevel=1.5)
>     237 
>     238         self.cmap = _read_ae_colormap(cmap="ae_orange", cmap_hex=True)
> 
> ~/src/climakitae/climakitae/warming_levels.py in get_anomaly_data(data, warmlevel, scenario)
>     100         gwl_times_subset = gwl_times[
>     101             (gwl_times["simulation"] == sim_str)
> --> 102             & (gwl_times["run"] == sim_and_runs_dict[sim_str])
>     103             & (gwl_times["scenario"] == scenario)
>     104         ]
> 
> KeyError: 'WRF_CESM2_r11i1p1f1'
> ```

Ah sorry, this is because this branch had diverged from main after I merged a different commit. Just merged main into this branch and it works now. Sorry to keep sending you on a wild goose chase!

**Comment by Tianchi-Liu** [comment]
Selecting station data in `app.select()` gives `NameError: name 'stations_gpd' is not defined`

```
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/pyviz_comms/__init__.py", line 325, in _handle_msg
    self._on_msg(msg)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/panel/viewable.py", line 273, in _on_msg
    doc.unhold()
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/bokeh/document/document.py", line 799, in unhold
    self.callbacks.unhold()
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/bokeh/document/callbacks.py", line 396, in unhold
    self.trigger_on_change(event)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/bokeh/document/callbacks.py", line 373, in trigger_on_change
    invoke_with_curdoc(doc, event.callback_invoker)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/bokeh/document/callbacks.py", line 408, in invoke_with_curdoc
    return f()
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/bokeh/util/callback_manager.py", line 191, in invoke
    callback(attr, old, new)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/panel/reactive.py", line 301, in _comm_change
    self._process_events({attr: new})
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/panel/reactive.py", line 262, in _process_events
    self.param.set_param(**self_events)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 1526, in set_param
    self_._batch_call_watchers()
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 1665, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 1627, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/panel/param.py", line 444, in link_widget
    self.object.param.set_param(**{p_name: change.new})
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 1526, in set_param
    self_._batch_call_watchers()
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 1665, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 1627, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 520, in caller
    return function()
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 351, in _depends
    return func(*args,**kw)
  File "/home/jovyan/src/climakitae/climakitae/selectors.py", line 1148, in _update_station_list
    self.station = overlapping_stations
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 316, in _f
    instance_param.__set__(obj, val)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 318, in _f
    return f(self, obj, val)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 984, in __set__
    obj.param._call_watcher(watcher, event)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 1645, in _call_watcher
    self_._execute_watcher(watcher, (event,))
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 1627, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 520, in caller
    return function()
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 351, in _depends
    return func(*args,**kw)
  File "/home/jovyan/src/climakitae/climakitae/selectors.py", line 1279, in map_view
    return _map_view(selections=self)
  File "/home/jovyan/src/climakitae/climakitae/selectors.py", line 491, in _map_view
    stations_selection_gpd = stations_gpd.loc[
NameError: name 'stations_gpd' is not defined
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/pyviz_comms/__init__.py", line 325, in _handle_msg
    self._on_msg(msg)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/panel/viewable.py", line 273, in _on_msg
    doc.unhold()
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/bokeh/document/document.py", line 799, in unhold
    self.callbacks.unhold()
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/bokeh/document/callbacks.py", line 396, in unhold
    self.trigger_on_change(event)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/bokeh/document/callbacks.py", line 373, in trigger_on_change
    invoke_with_curdoc(doc, event.callback_invoker)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/bokeh/document/callbacks.py", line 408, in invoke_with_curdoc
    return f()
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/bokeh/util/callback_manager.py", line 191, in invoke
    callback(attr, old, new)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/panel/reactive.py", line 301, in _comm_change
    self._process_events({attr: new})
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/panel/reactive.py", line 262, in _process_events
    self.param.set_param(**self_events)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 1526, in set_param
    self_._batch_call_watchers()
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 1665, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 1627, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/panel/param.py", line 444, in link_widget
    self.object.param.set_param(**{p_name: change.new})
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 1526, in set_param
    self_._batch_call_watchers()
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 1665, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 1627, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 520, in caller
    return function()
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 351, in _depends
    return func(*args,**kw)
  File "/home/jovyan/src/climakitae/climakitae/selectors.py", line 1279, in map_view
    return _map_view(selections=self)
  File "/home/jovyan/src/climakitae/climakitae/selectors.py", line 491, in _map_view
    stations_selection_gpd = stations_gpd.loc[
NameError: name 'stations_gpd' is not defined

```

**Comment by vicford** [comment]
> Selecting station data in `app.select()` gives `NameError: name 'stations_gpd' is not defined`

Confirming, I also get this behavior

**Review by vicford — APPROVED** [review]
stations selection in app.select now works!

**Review by Tianchi-Liu — APPROVED** [review]
Confirming that stations selection works now! 

The following error pops up when extreme lat/lon is selected, but the map displays as expected otherwise, so depending on whether extreme lat/lon selections are anticipated, up to you whether to merge or to look into the error.

```
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/pyviz_comms/__init__.py", line 325, in _handle_msg
    self._on_msg(msg)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/panel/viewable.py", line 273, in _on_msg
    doc.unhold()
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/bokeh/document/document.py", line 799, in unhold
    self.callbacks.unhold()
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/bokeh/document/callbacks.py", line 396, in unhold
    self.trigger_on_change(event)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/bokeh/document/callbacks.py", line 373, in trigger_on_change
    invoke_with_curdoc(doc, event.callback_invoker)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/bokeh/document/callbacks.py", line 408, in invoke_with_curdoc
    return f()
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/bokeh/util/callback_manager.py", line 191, in invoke
    callback(attr, old, new)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/panel/reactive.py", line 301, in _comm_change
    self._process_events({attr: new})
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/panel/reactive.py", line 262, in _process_events
    self.param.set_param(**self_events)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 1526, in set_param
    self_._batch_call_watchers()
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 1665, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 1627, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/panel/param.py", line 444, in link_widget
    self.object.param.set_param(**{p_name: change.new})
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 1526, in set_param
    self_._batch_call_watchers()
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 1665, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 1627, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 520, in caller
    return function()
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 351, in _depends
    return func(*args,**kw)
  File "/home/jovyan/src/climakitae/climakitae/selectors.py", line 520, in view
    ax.set_extent(extent, crs=xy)
UnboundLocalError: local variable 'extent' referenced before assignment
```

**Comment by nicolejkeeney** [comment]
> Confirming that stations selection works now!
> 
> The following error pops up when extreme lat/lon is selected, but the map displays as expected otherwise, so depending on whether extreme lat/lon selections are anticipated, up to you whether to merge or to look into the error.
> 
> ```
> Traceback (most recent call last):
>   File "/srv/conda/envs/notebook/lib/python3.9/site-packages/pyviz_comms/__init__.py", line 325, in _handle_msg
>     self._on_msg(msg)
>   File "/srv/conda/envs/notebook/lib/python3.9/site-packages/panel/viewable.py", line 273, in _on_msg
>     doc.unhold()
>   File "/srv/conda/envs/notebook/lib/python3.9/site-packages/bokeh/document/document.py", line 799, in unhold
>     self.callbacks.unhold()
>   File "/srv/conda/envs/notebook/lib/python3.9/site-packages/bokeh/document/callbacks.py", line 396, in unhold
>     self.trigger_on_change(event)
>   File "/srv/conda/envs/notebook/lib/python3.9/site-packages/bokeh/document/callbacks.py", line 373, in trigger_on_change
>     invoke_with_curdoc(doc, event.callback_invoker)
>   File "/srv/conda/envs/notebook/lib/python3.9/site-packages/bokeh/document/callbacks.py", line 408, in invoke_with_curdoc
>     return f()
>   File "/srv/conda/envs/notebook/lib/python3.9/site-packages/bokeh/util/callback_manager.py", line 191, in invoke
>     callback(attr, old, new)
>   File "/srv/conda/envs/notebook/lib/python3.9/site-packages/panel/reactive.py", line 301, in _comm_change
>     self._process_events({attr: new})
>   File "/srv/conda/envs/notebook/lib/python3.9/site-packages/panel/reactive.py", line 262, in _process_events
>     self.param.set_param(**self_events)
>   File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 1526, in set_param
>     self_._batch_call_watchers()
>   File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 1665, in _batch_call_watchers
>     self_._execute_watcher(watcher, events)
>   File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 1627, in _execute_watcher
>     watcher.fn(*args, **kwargs)
>   File "/srv/conda/envs/notebook/lib/python3.9/site-packages/panel/param.py", line 444, in link_widget
>     self.object.param.set_param(**{p_name: change.new})
>   File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 1526, in set_param
>     self_._batch_call_watchers()
>   File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 1665, in _batch_call_watchers
>     self_._execute_watcher(watcher, events)
>   File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 1627, in _execute_watcher
>     watcher.fn(*args, **kwargs)
>   File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 520, in caller
>     return function()
>   File "/srv/conda/envs/notebook/lib/python3.9/site-packages/param/parameterized.py", line 351, in _depends
>     return func(*args,**kw)
>   File "/home/jovyan/src/climakitae/climakitae/selectors.py", line 520, in view
>     ax.set_extent(extent, crs=xy)
> UnboundLocalError: local variable 'extent' referenced before assignment
> ```

Excellent find, I hadn't noticed this bug. It's unrelated to this PR (bug is present in main as well), so I'll make a trello card to address it later. Thanks!

**Pull request merged**
