### PR TITLE
SCE Pilot- Tech Debt Initial Tests Pt. 1

### PR DESCRIPTION
**Pull request by claalmve**
# Description of PR

**Summary of changes and related issue**
We want to have test coverage for `cava_data` and its respective helper functions. This PR creates tests for the helper functions of `cava_data`. A future PR will provide full test coverage over `cava_data` as well.

**Relevant motivation and context**
We want full test coverage so that when something breaks, we know about it.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

**Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.**
- `tests/vulnerability/test_vulnerability.py`

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by vicford** [comment]
Instructions for testing unit tests, because it's not listed (if this is wrong @claalmve please correct me): 
- On local machine, activate tests environment 
- `pip install pytest` (if not already present -- should be)
- `pytest tests/vulnerability/test_vulnerability.py`

**Comment by vicford** [comment]
I had to install the following packages for this test: `boto3`, `IPython`, `timezonefinder`

Upon running:
- Getting a failure on `test_export_no_e`: `AssertionError: The file should be created.`
- Getting a bunch of DeprecationWarnings. 
- Says there are 1 failures (test_export_no_e), 3 pass, 10 warnings.

**Comment by claalmve** [comment]
Also need to install `h5netcdf`

**Comment by elehmer** [comment]
> Also need to install `h5netcdf`

The testing environment uses the `conda-lock` file, not the `env.yml`. `h5netcdf` is installed in that environment (hopefully).

**Comment by elehmer** [comment]
The tests might be failing because of a version issue. Not all packages are exactly the same as on the HUB and we might be running into an incompatibility.

**Comment by vicford** [comment]
This is still failing for me @claalmve. On test_metric_agg it looks like

1 failed, 3 passed, 10 warnings

**Comment by vicford** [comment]
Alright, all 4 tests are passing on the hub! Failing locally (but I am also on a Mac OS)

**Pull request merged**
