### PR TITLE
Bigger refactor of data_loaders.py

### PR DESCRIPTION
**Pull request by thenaomig**
A bigger refactor of data_loaders.py -- 
- replacing `_process_and_concat` and `_subset` with a series of smaller functions
- fewer loops are present in building the multi-dimensional xr.DataArray 
- steps are more modular and testable

### CODE REVIEW

**Comment by nicolejkeeney** [comment]
The code fails when retrieving station data.

**Comment by thenaomig** [comment]
> The code fails when retrieving station data for more than one station :(

Actually, I see the problem, and it's not specific to selecting 'station': the code fails if you don't select an ssp.

**Comment by elehmer** [comment]
To fix the failing test env I added `pygeos=0.13` to the testing environment. The test still fails but not for any package issues.

**Comment by elehmer** [comment]
Test fixed by adding needed package `pyarrow` to testing environment. This package is needed to read parquet files.

**Review by nicolejkeeney — APPROVED** [review]
Looks good to me!!

**Review by elehmer — APPROVED** [review]
Looks good! You might want to merge main as the env.yml file has changed.

**Pull request merged**
