### PR TITLE
Update Read the Docs configuration

### PR DESCRIPTION
**Pull request by Tianchi-Liu**
# Description of PR

**Summary of changes and related issue**
- Update the order of requirements.txt and docs/requirements.txt installation in .readthedocs.yaml to install core dependencies first
- Add IPython to docs/requirements.txt
 
**Relevant motivation and context**
- Read the Docs fails to build from [time](https://github.com/cal-adapt/climakitae/pull/338) to [time](https://github.com/cal-adapt/climakitae/pull/349) due to dependency issues. This PR tries to stabilize the build processes by installing core dependencies first.
- IPython is introduced in `climakitae/explore/vulnerability.py` and needs to be installed for documentation to show up on Read the Docs.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

**Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.**

Build succeeded. Preview: https://climakitae--374.org.readthedocs.build/en/374/

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [not relevant] I have commented my code, particularly in hard-to-understand areas
- [not relevant] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [not relevant] New and existing unit tests pass locally with my changes
- [not relevant] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by elehmer — COMMENTED** [review]
I think we want to keep python version at 3.9.13 which is the version on the HUB.

Is there a reason for having so many packages in the readthedocs requirements? If it is only for setting up virtualenv locally for building files then what I do is first load the requirements.txt from the climakitae package and then load the requirements.txt here in the docs dir.

**Comment by Tianchi-Liu** [comment]
> Is there a reason for having so many packages in the readthedocs requirements? If it is only for setting up virtualenv locally for building files then what I do is first load the requirements.txt from the climakitae package and then load the requirements.txt here in the docs dir.

The packages are for setting up the remote builds as well. I hoped including them all would prevent some build failures due to dependency issues such as those that occurred recently.

**Comment by Tianchi-Liu** [comment]
@elehmer I reverted the updates, but added `ipython` to docs/requirements.txt. I also updated the order of req.txt and docs/req.txt installation in .readthedocs.yaml so the main requirements get installed first. Does this look better?

**Comment by elehmer** [comment]
> @elehmer I reverted the updates, but added `ipython` to docs/requirements.txt. I also updated the order of req.txt and docs/req.txt installation in .readthedocs.yaml so the main requirements get installed first. Does this look better?

Thanks for that as I think just the minimum to get readthedocs working is for the best.

Can you set `ipython==8.5.0`? That is what it is on the HUB. You can always check the version on the HUB by opening a Terminal and typing `conda list | grep <package_of_interest>`

**Pull request merged**
