### PR TITLE
Copy input attrs to output data in get_anomaly_data

### PR DESCRIPTION
**Pull request by elehmer**
This is a simple fix for #98 by setting the new Xarray DataSet created attributes to the attributes of the input DataArray. @vicford Can you check if all these attrs are appropriate to keep in the output data. If not we can pop out those ones.

### CODE REVIEW

**Review by vicford — APPROVED** [review]
Yep - all of these should be kept. I went back and forth on whether the window years should be kept, but as we add more models these will change so I do think it is important for clarity at each step that we are explicit about which years are being used computationally. 

Looks good to me - thanks for handling this

Screen Shot 2022-10-14 at 9 53 15 AM

**Comment by elehmer** [comment]
I probably should have branched off of #97 instead of #main...

**Review by nicolejkeeney — APPROVED** [review]
Looks good!

**Comment by nicolejkeeney** [comment]
> I probably should have branched off of #97 instead of #main...

I don't think it should cause any merge conflicts actually!

**Comment by elehmer** [comment]
> > I probably should have branched off of #97 instead of #main...
> 
> I don't think it should cause any merge conflicts actually!

Yes, this is a simple fix and will merge nicely. Going for merge now.

**Pull request merged**
