### PR TITLE
fixed bug that attempted to slice coordinate instead of dimension

### PR DESCRIPTION
**Pull request by bethmints**
fixing this bug exposed another one associated with exporting metadata attributes to a text file for csv/geotiff. This will be a part of a separate pull request (or potentially a larger conversation re: metadata).

### CODE REVIEW

**Comment by nicolejkeeney** [comment]
The export data function isn't acting as I would expect regarding data coords/dims. If I feed the export_dataset my simulation of choice as a kwarg, I would think that it would "slice" the data and only output a netcdf containing my simulation of choice. But, no slicing occurs and the entire dataset is downloaded. 
 
kwargs

**Comment by nicolejkeeney** [comment]
The function throws an error when you try to download the data using a filename that already exists in your directory. It would be nice to have this throw a custom error instead of the default scary red python error message. The actual error message that is thrown is `PermissionError: [Errno 13] Permission denied: b'/home/jovyan/cae-notebooks/cesm.nc'`, which occured because I already had a file named "cesm.nc" in my directory. Perhaps just a custom error, warning, or print message is better, i.e. `"A file named "cesm.nc" already exists in your directory. Please choose a different filename."`

error
error_2

**Review by nicolejkeeney — APPROVED** [review]
This all looks good to me. I left additional some comments about related issues, but you could address those in a separate PR.

**Comment by bethmints** [comment]
Ah, this is a good catch.

**Review by vicford — APPROVED** [review]
Specifically was able to raise the desired errors, but going to second @nicolejkeeney comment about unique filenames, that would be useful in a future iteration!

**Pull request closed without merging**
