### PR TITLE
Add Black lint checking to workflow

### PR DESCRIPTION
**Pull request by elehmer**
After reviewing the GitHub workflow documentation this looks like the best way to implement lint checking on the repo. With this workflow it didn't seem necessary for the other tests to be dependent on the lint. Also, this just checks the code and fails if not compliant. This would require the coder to run `black` before committing and pushing to pass the test. Or would we rather have the workflow reformat the code automatically? I'm not super sure how that would be done, but can look into it.

### CODE REVIEW

**Review by nicolejkeeney — CHANGES_REQUESTED** [review]
The tests for lint seem to be failing now, and I'm not sure how to interpret the error messages.

**Review by nicolejkeeney — APPROVED** [review]
Sorry, disregard my last comment. I realize that the failing tests are the purpose of this PR, haha! Am still concerned that the failed test error messages are hard to interpret.

**Comment by elehmer** [comment]
> Sorry, disregard my last comment. I realize that the failing tests are the purpose of this PR, haha! Am still concerned that the failed test error messages are hard to interpret.

Yep, basically if the lint test fails you forgot to run `black` before committing and pushing. So, we would just need to change our procedure for updating code.

**Comment by nicolejkeeney** [comment]
> > Sorry, disregard my last comment. I realize that the failing tests are the purpose of this PR, haha! Am still concerned that the failed test error messages are hard to interpret.
> 
> Yep, basically if the lint test fails you forgot to run `black` before committing and pushing. So, we would just need to change our procedure for updating code.

Got it, sounds good!

**Comment by elehmer** [comment]
It looks like we might be able to have it auto-commit `black` formatted code to the repo as an action, but it would be more complicated than just checking:

https://github.com/lgeiger/black-action/issues/1

**Comment by elehmer** [comment]
I'm going merge this. From now on in order to pass the `black` test you will have to run your code change through `black` and commit the changes. See the `black` documentation for more information:

https://github.com/psf/black

Basically, though, just add `black` to your environment and run `python -m black {source_file_or_directory}` and commit changes.

**Pull request merged**
