### PR TITLE
Remove global variables from modules

### PR DESCRIPTION
**Pull request by nicolejkeeney**
This PR removes global variables from all modules. 

**To test**: Just play around with climakitae (i.e. `app.select()`, `app.view()`, `app.explore...`) and make sure you don't find any weird bugs. 

Edit April 28: I fixed the warming levels bug and this PR is good to review now :D

### CODE REVIEW

**Review by elehmer — APPROVED** [review]
Looks good and works but didn't run every notebook.

**Comment by elehmer** [comment]
Oh missed the warming levels bug...

**Comment by nicolejkeeney** [comment]
> Oh missed the warming levels bug...

No worries-- I did too at first!

**Review by vicford — APPROVED** [review]
No issues now!

**Pull request merged**
