### PR TITLE
Unit conversion happening twice

### PR DESCRIPTION
**Pull request by nicolejkeeney**
# Description of PR

Looks like unit conversion was happening two times in the data retrieval code. An error was being raised for monthly precip data retrieval in the first conversion because the frequency attribute had not yet been added by that time in the workflow, raising an error for unit conversion. 

I'm not sure if this may raise other issues down the line. I tested a few conversions and it seems fine but maybe there are things I'm not thinking of. Time will tell...

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

**Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.**

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by nicolejkeeney** [comment]
[Assessing precip units issue](https://trello.com/c/DLbnk75l/708-assessing-precip-units-issue)

**Review by vicford — APPROVED** [review]
Now working in `historical_climate_data_comparisons` notebook!!

**Comment by claalmve** [comment]
I looked into the call stacks of this PR and `cksplit2a` when retrieving precip data, and this fix makes sense with me! It looks like the extra `convert_units` is happening on each individual dataset before they're merged together, and frequency is only added after the merge, so this fix makes sense to fix the issue at hand. What I'm not too sure about is why this only happens with precip retrieval and not other variables. Otherwise, LGTM!

**Review by claalmve — APPROVED** [review]

**Comment by nicolejkeeney** [comment]
> I looked into the call stacks of this PR and `cksplit2a` when retrieving precip data, and this fix makes sense with me! It looks like the extra `convert_units` is happening on each individual dataset before they're merged together, and frequency is only added after the merge, so this fix makes sense to fix the issue at hand. What I'm not too sure about is why this only happens with precip retrieval and not other variables. Otherwise, LGTM!

Thanks for checking the logic!! I'll merge it now

**Pull request merged**
