### PR TITLE
Update plots for threshold basics and application notebooks

### PR DESCRIPTION
**Pull request by Tianchi-Liu**
for [Threshold basics notebook update PR in cae-examples](https://github.com/cal-adapt/cae-examples/pull/39)

- label color bars with variable name and unit (if any)
- correct variable units in hover tooltips
- match plot title language with that elsewhere in the notebooks
- split plot titles into 2 lines to not have them cut off
- add variable unit to relevant plot titles

### CODE REVIEW

**Comment by nicolejkeeney** [comment]
You'll notice Eric added a new check to ensure the code passes formatting requirements. Right now it shows these tests are failing. To ensure your code is formatted "correctly" just do the following (in terminal) and push the changes: 
```
pip install black 
python -m black climakitae 
```
Then, the "lint" tests should pass!

**Review by vicford — APPROVED** [review]
Nice work Tianchi! I tested for both K and degC and the plots update nicely

**Comment by Tianchi-Liu** [comment]
> You'll notice Eric added a new check to ensure the code passes formatting requirements. Right now it shows these tests are failing. To ensure your code is formatted "correctly" just do the following (in terminal) and push the changes:
> 
> ```
> pip install black 
> python -m black climakitae 
> ```
> 
> Then, the "lint" tests should pass!

**Review by nicolejkeeney — APPROVED** [review]
Looks good to me!

**Pull request merged**
