### PR TITLE
Change function to convert calendar to noleapyear for station data

### PR DESCRIPTION
**Pull request by elehmer**
This PR replaces `xclim.core.calendar.convert_calendar` which outputs `CFTime` with `xarray.Dataset.convert_calendar` which outputs `datetime64`.

### CODE REVIEW

**Comment by vicford** [comment]
Getting an interesting warning: `/srv/conda/envs/notebook/lib/python3.9/site-packages/xclim/sdba/adjustment.py:118: UserWarning: Strange results could be returned when using dayofyear grouping on data defined in the proleptic_gregorian calendar `

**Comment by elehmer** [comment]
Yeah we have issues with the QuantileDeltaMapping now...

**Review by bethem — COMMENTED** [review]
I've pushed a new PR to this branch - which maybe I should not have done.

**Comment by elehmer** [comment]
This seems to work well. Going to merge

**Pull request merged**
